#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . './Commands/createCartCommand.php';
require_once __DIR__ . './Commands/createProductCommand.php';
require_once __DIR__ . './Includes/FactoryDB.php';
require_once __DIR__ . './config/db.php';

use Commands\createCartCommand;

use Commands\createProductCommand;
use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new createCartCommand());
$application->add(new  createProductCommand());

$application->run();
